# Generated by Django 3.1.5 on 2021-01-14 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namecollect', '0002_auto_20210114_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(125, 'Age must be less than 126')]),
        ),
    ]
